<a href="https://colab.research.google.com/github/xayrullofayzullaev13-netizen/week1_lab/blob/main/Lab2_Fund_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2: Matrix Fundamentals in NumPy

- **Course:** CSE206 Fundamentals of Machine Learning
- **Department:** Information Technology and Engineering, Amity University Tashkent
- **Duration:** 2 hours
- **Format:** Session 1 (60 min) guided walkthrough | Session 2 (60 min) graded exercises, 100 marks

---

### What you will learn today

1. What NumPy is and why machine learning uses it.
2. The difference between 1-D arrays (vectors), 2-D arrays (matrices) and 3-D arrays.
3. How to select values, rows and columns.
4. Addition, subtraction and multiplication of arrays.
5. Absolute values and negation.
6. Adding and removing elements, rows and columns.
7. Maximum, minimum and sum.
8. Transpose and vectorized (loop-free) arithmetic.

### Lab plan

| Part | Topic | Time |
|---|---|---|
| 1.0 | What is NumPy? | 5 min |
| 1.1 | Arrays in 1, 2 and 3 dimensions | 8 min |
| 1.2 | Selecting values, rows and columns | 9 min |
| 1.3 | Addition and subtraction | 6 min |
| 1.4 | Multiplication | 8 min |
| 1.5 | Absolute values and negation | 4 min |
| 1.6 | Adding and removing elements, rows and columns | 8 min |
| 1.7 | Maximum, minimum and sum | 7 min |
| 1.8 | Transpose and vectorized arithmetic | 5 min |
| 2 | Graded exercises 1 to 10 | 60 min |

---
# Session 1: Guided Walkthrough

## 1.0 What is NumPy?

**NumPy** (Numerical Python) is the main Python library for working with numbers in tables. Almost every machine learning library (scikit-learn, pandas, PyTorch) is built on the same idea.

The central object in NumPy is the **array**: a grid of numbers that all have the same type.

In machine learning, data is stored in arrays:

- one student's marks in 4 subjects is a **1-D array** (a list of numbers),
- the marks of the whole class is a **2-D array** (a table),
- a colour image is a **3-D array** (height x width x colour channels).

We always start by importing NumPy with the short name `np`.

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


### Python list vs NumPy array

A Python list and a NumPy array look similar, but they behave differently. With a list, `+` joins the two lists. With an array, `+` adds the numbers.

In [ ]:
list_a = [1, 2, 3]
list_b = [10, 20, 30]
print("List  + List :", list_a + list_b)      # joins the lists

arr_a = np.array([1, 2, 3])
arr_b = np.array([10, 20, 30])
print("Array + Array:", arr_a + arr_b)        # adds element by element

## 1.1 Arrays in 1, 2 and 3 dimensions

| Name | Dimensions (`ndim`) | Example `shape` | Picture |
|---|---|---|---|
| Scalar | 0 | `()` | one number |
| Vector | 1 | `(4,)` | a single row of 4 numbers |
| Matrix | 2 | `(2, 3)` | a table with 2 rows and 3 columns |
| 3-D array | 3 | `(2, 2, 3)` | 2 tables stacked on top of each other, each 2 x 3 |

Three attributes describe every array:

- `ndim`: how many dimensions it has
- `shape`: how many elements along each dimension
- `size`: the total number of elements

In [ ]:
# 0-D: a single number (scalar)
s = np.array(5)

# 1-D: a vector, written as one list
v = np.array([4, 7, 1, 9])

# 2-D: a matrix, written as a list of rows
M = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3-D: a list of matrices
T = np.array([[[1, 2, 3],
               [4, 5, 6]],

              [[7, 8, 9],
               [10, 11, 12]]])

for name, arr in [("s", s), ("v", v), ("M", M), ("T", T)]:
    print(f"{name}: ndim = {arr.ndim}, shape = {arr.shape}, size = {arr.size}")

In [ ]:
print("Vector v:")
print(v)
print("\nMatrix M:")
print(M)
print("\n3-D array T (NumPy prints each inner matrix separately):")
print(T)

**How to read a shape:**

- `(4,)` means 4 elements in a line. The comma tells you it is 1-D.
- `(2, 3)` means 2 rows and 3 columns.
- `(2, 2, 3)` means 2 blocks, each with 2 rows and 3 columns.

### Ready-made arrays

You do not always need to type the numbers. NumPy can build arrays for you. You pass the shape you want.

In [ ]:
print("1-D zeros, shape (5,):")
print(np.zeros(5))

print("\n2-D ones, shape (2, 3):")
print(np.ones((2, 3)))

print("\n3-D zeros, shape (2, 2, 2):")
print(np.zeros((2, 2, 2)))

print("\n2-D identity matrix, shape (3, 3):")
print(np.eye(3))

`np.arange(start, stop)` makes a 1-D array of whole numbers from `start` up to **but not including** `stop`.
`reshape` rearranges the same numbers into a new shape. The total number of elements must stay the same.

In [ ]:
numbers = np.arange(1, 13)          # 1-D, 12 numbers
print("1-D, shape", numbers.shape)
print(numbers)

as_matrix = numbers.reshape(3, 4)   # 2-D, 3 x 4 = 12
print("\n2-D, shape", as_matrix.shape)
print(as_matrix)

as_3d = numbers.reshape(2, 2, 3)    # 3-D, 2 x 2 x 3 = 12
print("\n3-D, shape", as_3d.shape)
print(as_3d)

In [ ]:
# 12 numbers cannot fill a 5 x 3 table (15 places), so NumPy gives an error.
try:
    numbers.reshape(5, 3)
except ValueError as e:
    print("Error:", e)

### A real 3-D example: a tiny colour image

A colour image is stored as `(height, width, 3)`. The last dimension holds the Red, Green and Blue values (0 to 255) of each pixel. Below is a 2 x 2 image.

In [ ]:
image = np.array([[[255,   0,   0], [  0, 255,   0]],     # top row: red pixel, green pixel
                  [[  0,   0, 255], [255, 255, 255]]])    # bottom row: blue pixel, white pixel

print("shape:", image.shape, "-> 2 rows of pixels, 2 columns of pixels, 3 colour values")
print("ndim :", image.ndim)

## 1.2 Selecting values, rows and columns

**Indexing starts at 0.** The first element has index 0, the second has index 1, and so on. Index `-1` means the last element.

### 1-D: one index

| Expression | Meaning |
|---|---|
| `v[0]` | first element |
| `v[-1]` | last element |
| `v[1:4]` | elements at index 1, 2, 3 (the end index 4 is not included) |
| `v[:3]` | the first three elements |

In [ ]:
temps = np.array([18, 21, 25, 23, 19, 16, 20])   # temperature for 7 days
print("temps      :", temps)
print("temps[0]   :", temps[0])
print("temps[-1]  :", temps[-1])
print("temps[1:4] :", temps[1:4])
print("temps[:3]  :", temps[:3])

### 2-D: two indices, `[row, column]`

A colon `:` means "all".

| Expression | Meaning |
|---|---|
| `M[1, 2]` | the value in row 1, column 2 |
| `M[0]` or `M[0, :]` | the whole row 0 |
| `M[:, 1]` | the whole column 1 |
| `M[0:2, 0:2]` | rows 0 to 1 and columns 0 to 1 |
| `M[[0, 2]]` | rows 0 and 2 |
| `M[:, [0, 3]]` | columns 0 and 3 |

We use a table of exam marks: 4 students (rows) and 3 subjects (columns: Math, Physics, English).

In [ ]:
marks = np.array([[78, 85, 70],    # student 0
                  [64, 58, 88],    # student 1
                  [90, 94, 81],    # student 2
                  [55, 62, 73]])   # student 3

print(marks)
print("shape:", marks.shape)

In [ ]:
print("Student 2, Physics  (marks[2, 1]):", marks[2, 1])
print("Row of student 1    (marks[1])   :", marks[1])
print("Column Math         (marks[:, 0]):", marks[:, 0])

In [ ]:
print("First two students, first two subjects:")
print(marks[0:2, 0:2])

print("\nStudents 0 and 2 only:")
print(marks[[0, 2]])

print("\nMath and English columns only:")
print(marks[:, [0, 2]])

**Selecting with a condition.** A comparison gives an array of `True` / `False` values. We can use it to keep only matching values.

In [ ]:
print("temps > 20      :", temps > 20)
print("temps above 20  :", temps[temps > 20])

print("\nStudents with Math >= 75:")
print(marks[marks[:, 0] >= 75])

### 3-D: three indices, `[block, row, column]`

For our image, `image[row, column]` gives one pixel (3 colour values) and `image[row, column, channel]` gives a single number.

In [ ]:
print("Top-left pixel      image[0, 0]   :", image[0, 0])
print("Its green value     image[0, 0, 1]:", image[0, 0, 1])
print("\nRed channel of every pixel image[:, :, 0]:")
print(image[:, :, 0])

## 1.3 Addition and subtraction

When two arrays have the **same shape**, `+` and `-` work **element by element**: each value is combined with the value in the same position. This works the same way for 1-D, 2-D and 3-D arrays.

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} +
\begin{bmatrix} 10 & 0 \\ 20 & 30 \end{bmatrix} =
\begin{bmatrix} 11 & 2 \\ 23 & 34 \end{bmatrix}
$$

In [ ]:
# 1-D
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("1-D  a + b =", a + b)
print("1-D  b - a =", b - a)

# 2-D
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[10,  0],
              [20, 30]])
print("\n2-D  A + B =")
print(A + B)
print("2-D  B - A =")
print(B - A)

# 3-D
T1 = np.ones((2, 2, 2))
T2 = np.full((2, 2, 2), 5)
print("\n3-D  T2 - T1 =")
print(T2 - T1)

**Adding a single number (a scalar)** adds it to every element, whatever the shape.

In [ ]:
print("a + 100 =", a + 100)
print("A + 100 =")
print(A + 100)

**Broadcasting.** A 1-D array can be added to every row of a 2-D array when its length equals the number of columns.

In [ ]:
bonus = np.array([5, 0, 2])       # one bonus per subject, shape (3,)
print("marks shape:", marks.shape, " bonus shape:", bonus.shape)
print(marks + bonus)              # bonus is added to every student's row

In [ ]:
# Shapes that do not match give an error
try:
    a + np.array([1, 2])          # shape (3,) + shape (2,)
except ValueError as e:
    print("Error:", e)

## 1.4 Multiplication

NumPy has **two kinds** of multiplication. Mixing them up is the most common beginner mistake.

| Kind | Symbol | What it does | Shape rule |
|---|---|---|---|
| Element-wise | `*` | multiplies values in the same position | same shape |
| Dot / matrix product | `@` | rows times columns, then add up | columns of left = rows of right |

### Element-wise multiplication `*`

In [ ]:
# 1-D: price of each item x quantity of each item
price = np.array([2.0, 5.0, 1.5])
qty   = np.array([3,   1,   4])
print("price * qty =", price * qty)

# 2-D
print("\nA * B =")
print(A * B)

# Scalar times an array
print("\n3 * A =")
print(3 * A)

### Dot product of two vectors (1-D `@` 1-D)

Multiply matching elements and add them up. The result is a single number.

$$ [2, 5, 1.5] \cdot [3, 1, 4] = 2 \cdot 3 + 5 \cdot 1 + 1.5 \cdot 4 = 17 $$

In [ ]:
print("price @ qty =", price @ qty)            # total bill
print("same as     =", np.sum(price * qty))

### Matrix product (2-D `@` 2-D)

If `A` has shape `(m, n)` and `B` has shape `(n, p)`, then `A @ B` has shape `(m, p)`. The two inner numbers must be equal.

Each value of the result is a dot product: **row i of A** with **column j of B**.

$$
\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
\begin{bmatrix} 10 & 0 \\ 20 & 30 \end{bmatrix} =
\begin{bmatrix} 1\cdot10 + 2\cdot20 & 1\cdot0 + 2\cdot30 \\ 3\cdot10 + 4\cdot20 & 3\cdot0 + 4\cdot30 \end{bmatrix} =
\begin{bmatrix} 50 & 60 \\ 110 & 120 \end{bmatrix}
$$

In [ ]:
print("A * B (element-wise):")
print(A * B)
print("\nA @ B (matrix product):")
print(A @ B)

In [ ]:
# Order matters: A @ B is usually different from B @ A
print("A @ B:")
print(A @ B)
print("B @ A:")
print(B @ A)

In [ ]:
# Different shapes: (2, 3) @ (3, 2) -> (2, 2)
P = np.array([[1, 2, 3],
              [4, 5, 6]])        # shape (2, 3)
Q = np.array([[1, 0],
              [0, 1],
              [1, 1]])           # shape (3, 2)
print("P @ Q, shape", (P @ Q).shape)
print(P @ Q)

# (2, 3) @ (2, 3): inner numbers 3 and 2 are different -> error
try:
    P @ P
except ValueError as e:
    print("\nP @ P gives an error because 3 is not equal to 2")

### Matrix times vector (2-D `@` 1-D)

This is how a machine learning model makes predictions: each row of data is multiplied by the same weights.

In [ ]:
weights = np.array([0.5, 0.3, 0.2])      # importance of Math, Physics, English
final_score = marks @ weights            # (4, 3) @ (3,) -> (4,)
print("Weighted final score of each student:", final_score)

## 1.5 Absolute values and negation

- `np.abs(x)` removes the minus sign from every element.
- `-x` changes the sign of every element.

Both work on arrays of any dimension.

In [ ]:
d1 = np.array([-3, 5, -1, 0])
print("1-D  d1         :", d1)
print("     np.abs(d1) :", np.abs(d1))
print("     -d1        :", -d1)

d2 = np.array([[-2,  4],
               [ 7, -9]])
print("\n2-D  np.abs(d2):")
print(np.abs(d2))
print("     -d2:")
print(-d2)

d3 = np.array([[[-1, 2], [3, -4]],
               [[-5, 6], [7, -8]]])
print("\n3-D  np.abs(d3):")
print(np.abs(d3))

**Machine learning use:** the *Mean Absolute Error* (MAE) measures how far predictions are from the true values, ignoring whether they are too high or too low.

$$ \text{MAE} = \text{mean}\big(|y_{true} - y_{pred}|\big) $$

In [ ]:
y_true = np.array([3.0, 5.0, 2.0, 7.0])
y_pred = np.array([2.5, 6.0, 2.0, 8.0])

errors = y_true - y_pred
print("errors          :", errors)
print("absolute errors :", np.abs(errors))
print("MAE             :", np.mean(np.abs(errors)))

## 1.6 Adding and removing elements, rows and columns

These functions **return a new array**. The original stays the same unless you save the result back into it.

| Task | 1-D | 2-D |
|---|---|---|
| Add at the end | `np.append(v, value)` | row: `np.vstack([M, row])`, column: `np.column_stack([M, col])` |
| Remove | `np.delete(v, index)` | row: `np.delete(M, index, axis=0)`, column: `np.delete(M, index, axis=1)` |

**`axis` in 2-D:** `axis=0` means rows, `axis=1` means columns.

### 1-D

In [ ]:
v = np.array([4, 7, 1, 9])
print("v                      :", v)
print("np.append(v, 5)        :", np.append(v, 5))
print("np.append(v, [5, 6])   :", np.append(v, [5, 6]))
print("np.delete(v, 0)        :", np.delete(v, 0))       # remove index 0
print("np.delete(v, [1, 3])   :", np.delete(v, [1, 3]))  # remove index 1 and 3
print("v is unchanged         :", v)

### 2-D

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

new_row = np.array([7, 8, 9])
print("Add a row at the bottom (vstack):")
print(np.vstack([M, new_row]))

new_col = np.array([10, 20])
print("\nAdd a column on the right (column_stack):")
print(np.column_stack([M, new_col]))

In [ ]:
print("M:")
print(M)
print("\nRemove row 0 (axis=0):")
print(np.delete(M, 0, axis=0))
print("\nRemove column 1 (axis=1):")
print(np.delete(M, 1, axis=1))

### From 2-D to 3-D

`np.stack` puts several matrices of the same shape on top of each other, which creates a new dimension.

In [ ]:
week1 = np.array([[5, 3],
                  [2, 8]])
week2 = np.array([[6, 1],
                  [4, 7]])

both_weeks = np.stack([week1, week2])
print("shape:", week1.shape, "->", both_weeks.shape)
print(both_weeks)

In [ ]:
# Machine learning use: add a column of ones (the "bias" column) to a data table
X = np.array([[2.0, 3.0],
              [1.0, 5.0],
              [4.0, 1.0]])
X_bias = np.column_stack([np.ones(3), X])
print("shape:", X.shape, "->", X_bias.shape)
print(X_bias)

## 1.7 Maximum, minimum and sum

### 1-D: one answer for the whole array

In [ ]:
print("temps        :", temps)
print("max          :", temps.max())
print("min          :", temps.min())
print("sum          :", temps.sum())
print("mean         :", temps.mean())
print("argmax       :", temps.argmax(), " <- index (day) of the highest value")
print("argmin       :", temps.argmin(), " <- index (day) of the lowest value")

### 2-D: use `axis` to choose the direction

```
                 axis=1  (across each row)  --->
              Math  Physics  English
student 0  [   78      85       70   ]     row result: one value per student
student 1  [   64      58       88   ]
student 2  [   90      94       81   ]
student 3  [   55      62       73   ]
                |
    axis=0      |   column result: one value per subject
  (down each    v
   column)
```

- no `axis`: one value for the whole table
- `axis=0`: one value per **column**
- `axis=1`: one value per **row**

In [ ]:
print("Highest mark in the whole table  :", marks.max())
print("Highest mark in each subject     :", marks.max(axis=0))
print("Lowest mark of each student      :", marks.min(axis=1))
print("Total marks of each student      :", marks.sum(axis=1))
print("Average of each subject          :", marks.mean(axis=0))
print("Best student in each subject     :", marks.argmax(axis=0))

### 3-D: the same idea with one more direction

In [ ]:
print("both_weeks (week, row, column):")
print(both_weeks)
print("\nTotal of everything          :", both_weeks.sum())
print("Total of each week (2 values):", both_weeks.sum(axis=(1, 2)))
print("\nSum of the two weeks (axis=0), a 2x2 matrix:")
print(both_weeks.sum(axis=0))

## 1.8 Transpose and vectorized arithmetic

### Transpose

The **transpose** swaps rows and columns: row 0 becomes column 0, row 1 becomes column 1, and so on. In NumPy it is written `.T`.

- A 2-D array of shape `(2, 3)` becomes `(3, 2)`.
- A 1-D array has no rows and columns, so `.T` does **not** change it.

In [ ]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print("M, shape", M.shape)
print(M)
print("\nM.T, shape", M.T.shape)
print(M.T)
print("\nTranspose twice gives M back:", np.array_equal(M.T.T, M))

In [ ]:
v = np.array([1, 2, 3])
print("1-D v.shape  :", v.shape, " v.T.shape:", v.T.shape, "(no change)")

# A 2-D row vector (1 row, 3 columns) does change
row = np.array([[1, 2, 3]])
print("2-D row.shape:", row.shape, " row.T.shape:", row.T.shape)
print(row.T)

In [ ]:
# Transpose is often needed before a matrix product.
# M is (2, 3). M @ M is not allowed, but M.T @ M is (3, 2) @ (2, 3) -> (3, 3)
print("M.T @ M, shape", (M.T @ M).shape)
print(M.T @ M)

### Vectorized arithmetic

**Vectorized** code works on the whole array at once, with no `for` loop. It is shorter, easier to read and much faster, because NumPy runs the loop inside fast compiled code.

Example: convert 500,000 temperatures from Celsius to Fahrenheit, $F = C \times 1.8 + 32$.

In [ ]:
import time

celsius = np.arange(500_000) % 40            # half a million temperatures

# With a Python loop
start = time.perf_counter()
fahr_loop = []
for c in celsius:
    fahr_loop.append(c * 1.8 + 32)
t_loop = time.perf_counter() - start

# Vectorized: one line, no loop
start = time.perf_counter()
fahr_vec = celsius * 1.8 + 32
t_vec = time.perf_counter() - start

print(f"Loop       : {t_loop:.3f} seconds")
print(f"Vectorized : {t_vec:.4f} seconds")
print(f"Vectorized is about {t_loop / t_vec:.0f} times faster")
print("Same results:", np.allclose(fahr_loop, fahr_vec))

### Putting it all together: predictions of a simple model

A linear model predicts a house price from its features with $\hat{y} = X w + b$:

- `X`: data table, one row per house (2-D)
- `w`: one weight per feature (1-D)
- `b`: a single number (the bias)

One line of vectorized code gives predictions for all houses at once.

In [ ]:
# 4 houses, 2 features: area (in 100 m^2) and number of rooms
X = np.array([[1.2, 3],
              [0.8, 2],
              [1.5, 4],
              [2.0, 5]])
y = np.array([130, 85, 160, 215])     # true prices (in 1000 USD)

w = np.array([80, 10])                # weights
b = 5                                 # bias

y_hat = X @ w + b                     # matrix x vector, then add a scalar
errors = y - y_hat

print("Predictions :", y_hat)
print("Errors      :", errors)
print("MAE         :", np.mean(np.abs(errors)))
print("MSE         :", np.mean(errors ** 2))

## Session 1 summary

| Topic | What to remember |
|---|---|
| Create | `np.array`, `np.zeros`, `np.ones`, `np.full`, `np.eye`, `np.arange`, `.reshape` |
| Describe | `.ndim`, `.shape`, `.size` |
| Select (1-D) | `v[0]`, `v[-1]`, `v[1:4]`, `v[v > 20]` |
| Select (2-D) | `M[r, c]`, `M[r]`, `M[:, c]`, `M[0:2, 0:2]`, `M[[0, 2]]` |
| Select (3-D) | `T[b]`, `T[b, r]`, `T[b, r, c]` |
| Add / subtract | `+`, `-` element by element, same shape (or a scalar) |
| Multiply | `*` element-wise, `@` dot / matrix product |
| Absolute / negate | `np.abs(x)`, `-x` |
| Add / remove | `np.append`, `np.delete`, `np.vstack`, `np.column_stack`, `np.stack` |
| Max / min / sum | `.max()`, `.min()`, `.sum()`, `.mean()`, `.argmax()`, `axis=0` columns, `axis=1` rows |
| Transpose | `M.T` swaps rows and columns, no effect on 1-D |
| Vectorize | write `X @ w + b`, not a `for` loop |

**Common mistakes**

1. Forgetting that indexing starts at 0.
2. Using `*` when you need `@`.
3. Mixing up `axis=0` (per column) and `axis=1` (per row).
4. Forgetting that `np.append` and `np.delete` return a new array.

---
# Session 2: Graded Exercises (100 marks, 60 minutes)

### Instructions

1. Work **on your own**. You may look at Session 1 above.
2. Find each line that ends with `# YOUR CODE HERE` and replace `None` with your code. **Do not change the variable names.**
3. For written parts, type your answer in the cell below **Your answer**.
4. Run each cell after you finish it and check the printed result.
5. Before submitting, select **Kernel > Restart & Run All** and make sure there are no errors.
6. Save the file as `StudentID_Lab2.ipynb` and upload it.

**Example of how to answer:**

```python
total = None  # YOUR CODE HERE      <- before
total = a + b  # YOUR CODE HERE     <- after
```

### Marks overview

| Exercise | Topic | Marks |
|---|---|---|
| 1 | Creating arrays in 1-D, 2-D and 3-D | 10 |
| 2 | Selecting from 1-D and 2-D arrays | 10 |
| 3 | Selecting from a 3-D array | 10 |
| 4 | Addition and subtraction | 10 |
| 5 | Multiplication | 10 |
| 6 | Absolute values and negation | 10 |
| 7 | Adding and removing elements, rows and columns | 10 |
| 8 | Maximum, minimum and sum | 10 |
| 9 | Transpose | 10 |
| 10 | Vectorized arithmetic: a small prediction model | 10 |
| | **Total** | **100** |

Run the setup cell below first.

In [ ]:
import numpy as np

def show(label, value):
    # Prints your answer, or a reminder if you have not answered yet.
    if value is None:
        print(f"{label}: not answered yet")
    else:
        print(f"{label}:\n{value}\n")

## Exercise 1: Creating arrays in 1-D, 2-D and 3-D (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | `v`: a 1-D array with the values 3, 6, 9, 12, 15. | 2 |
| (b) | `M`: a 2-D array with 2 rows: `[1, 2, 3]` and `[4, 5, 6]`. | 2 |
| (c) | `T`: a 3-D array of shape `(2, 2, 3)` that contains the numbers 1 to 12. Use `np.arange` and `reshape`. | 2 |
| (d) | `Z`: a 3x3 matrix of zeros. `O`: a 1-D array of five ones. | 2 |
| (e) | `v_ndim`, `M_ndim`, `T_ndim`: the number of dimensions of `v`, `M` and `T`. `T_shape`: the shape of `T`. | 2 |

In [ ]:
# (a)
v = np.array([3,6,9,12,15])  # YOUR CODE HERE

# (b)
M = np.array([
    [1,2,3],
    [4,5,6]
])  # YOUR CODE HERE

# (c)
T = np.arange(1, 13).reshape(2, 2, 3)  # YOUR CODE HERE

# (d)
Z = np.zeros((3, 3))  # YOUR CODE HERE
O = np.ones (5)  # YOUR CODE HERE

# (e)
v_ndim = v.ndim  # YOUR CODE HERE
M_ndim = M.ndim  # YOUR CODE HERE
T_ndim = T.ndim  # YOUR CODE HERE
T_shape = T.shape  # YOUR CODE HERE

print("v", v)
print("M", M)
print("T", T)
print("Z", Z)
print("O", O)
print("v_ndim", v_ndim)
print("M_ndim", M_ndim)
print("T_ndim", T_ndim)
print("T_shape", T_shape)

v [ 3  6  9 12 15]
M [[1 2 3]
 [4 5 6]]
T [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Z [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
O [1. 1. 1. 1. 1.]
v_ndim 1
M_ndim 2
T_ndim 3
T_shape (2, 2, 3)


## Exercise 2: Selecting from 1-D and 2-D arrays (10 marks)

`rain` is the rainfall (mm) for 7 days (1-D).
`scores` holds the marks of 4 students (rows 0 to 3) in 3 subjects (columns 0 to 2: Math, Physics, English).

| Part | Task | Marks |
|---|---|---|
| (a) | `first_day` and `last_day`: the first and the last value of `rain`. | 2 |
| (b) | `mid_days`: the rainfall of the days with index 2, 3 and 4. | 2 |
| (c) | `student1`: all marks of student 1 (a whole row). | 2 |
| (d) | `physics`: the Physics marks of all students (a whole column). | 2 |
| (e) | `s3_math`: the Math mark of student 3. `top_left`: the first two students in the first two subjects (a 2x2 matrix). | 2 |

In [ ]:
rain = np.array([0, 12, 5, 30, 8, 0, 17])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

first_day = rain[0]  # YOUR CODE HERE
last_day = rain[-1]  # YOUR CODE HERE

mid_days = rain[2:5]  # YOUR CODE HERE

student1 = scores[1]  # YOUR CODE HERE

physics = scores[:,1]  # YOUR CODE HERE

s3_math = scores[2,0]  # YOUR CODE HERE
top_left = scores[0:2,0:2]   # YOUR CODE HERE

print("first_day", first_day)
print("last_day", last_day)
print("mid_days", mid_days)
print("student1", student1)
print("physics", physics)
print("s3_math", s3_math)
print("top_left", top_left)

first_day 0
last_day 17
mid_days [ 5 30  8]
student1 [85 79 90]
physics [88 79 71 84]
s3_math 60
top_left [[72 88]
 [85 79]]


## Exercise 3: Selecting from a 3-D array (10 marks)

`sales` is a 3-D array with shape `(2, 3, 4)`:

- dimension 0: the **week** (0 or 1)
- dimension 1: the **store** (0, 1 or 2)
- dimension 2: the **product** (0, 1, 2 or 3)

So `sales[w, s, p]` is the number of units of product `p` sold in store `s` during week `w`.

| Part | Task | Marks |
|---|---|---|
| (a) | `sales_ndim` and `sales_shape`: the number of dimensions and the shape of `sales`. | 2 |
| (b) | `week0`: all sales of week 0 (a 3x4 matrix). | 2 |
| (c) | `w1_store2`: the sales of store 2 in week 1 (4 values). | 2 |
| (d) | `one_value`: the units of product 3 sold in store 0 during week 0. | 2 |
| (e) | `w1_product0`: the sales of product 0 in every store during week 1 (3 values). | 2 |

In [23]:
import numpy as np

sales = np.array([
    [[12,  7, 30,  4],
     [ 9, 15, 22,  6],
     [20,  3, 18, 11]],

    [[14,  5, 28,  9],
     [11, 15, 25,  2],
     [17,  8, 21, 13]]
])


sales_ndim =  sales.ndim  # YOUR CODE HERE
sales_shape = sales.shape  # YOUR CODE HERE

week0 = sales[0]  # YOUR CODE HERE

w1_store2 = sales[1, 2]  # YOUR CODE HERE

one_value = sales[0, 0, 3]  # YOUR CODE HERE

w1_product0 = sales[1, :, 0]  # YOUR CODE HERE

print("sales_ndim", sales_ndim)
print("sales_shape", sales_shape)
print("week0", week0)
print("w1_store2", w1_store2)
print("one_value", one_value)
print("w1_product0", w1_product0)

sales_ndim 3
sales_shape (2, 3, 4)
week0 [[12  7 30  4]
 [ 9 15 22  6]
 [20  3 18 11]]
w1_store2 [17  8 21 13]
one_value 4
w1_product0 [14 11 17]


## Exercise 4: Addition and subtraction (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `ab_sum` is `a` plus `b`, and `ab_diff` is `b` minus `a`. | 2 |
| (b) | 2-D: `total` is the sales of `jan` and `feb` added together, and `change` is `feb` minus `jan`. | 2 |
| (c) | 3-D: `T_sum` is `T1` plus `T2`. | 2 |
| (d) | `jan_plus10`: add 10 to every value of `jan`. | 2 |
| (e) | `jan_bonus`: add the 1-D array `bonus` to every row of `jan`. | 2 |

In [14]:
import numpy as np

a = np.array([4, 8, 15, 16])
b = np.array([10, 20, 30, 40])

jan = np.array([[5, 3, 8],
                [2, 7, 4]])
feb = np.array([[6, 1, 9],
                [4, 7, 2]])

T1 = np.arange(8).reshape(2, 2, 2)
T2 = np.full((2, 2, 2), 10)

bonus = np.array([1, 0, 5])

ab_sum = a + b  # YOUR CODE HERE
ab_diff = b - a  # YOUR CODE HERE

total = jan + feb  # YOUR CODE HERE
change = feb - jan  # YOUR CODE HERE

T_sum = T1 + T2  # YOUR CODE HERE

jan_plus10 = jan + 10  # YOUR CODE HERE

jan_bonus = jan + bonus  # YOUR CODE HERE

print("ab_sum", ab_sum)
print("ab_diff", ab_diff)
print("total", total)
print("change", change)
print("T_sum", T_sum)
print("jan_plus10", jan_plus10)
print("jan_bonus", jan_bonus)

ab_sum [14 28 45 56]
ab_diff [ 6 12 15 24]
total [[11  4 17]
 [ 6 14  6]]
change [[ 1 -2  1]
 [ 2  0 -2]]
T_sum [[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]
jan_plus10 [[15 13 18]
 [12 17 14]]
jan_bonus [[ 6  3 13]
 [ 3  7  9]]


## Exercise 5: Multiplication (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `cost` is the cost of each item (`price` times `qty`, element-wise). | 2 |
| (b) | 1-D: `bill` is the total bill, computed as the **dot product** of `price` and `qty`. | 2 |
| (c) | 2-D: `elem` is the element-wise product of `A` and `B`. `prod` is the matrix product of `A` and `B`. | 2 |
| (d) | `PC` is the matrix product of `P` (2x3) and `C` (3x2), and `PC_shape` is its shape. | 2 |
| (e) | Written: explain why `C @ C` gives an error. | 2 |

In [24]:
price = np.array([2.5, 4.0, 1.0, 10.0])
qty = np.array([4, 2, 10, 1])

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 3]])

P = np.array([[1, 2, 3],
              [4, 5, 6]])
C = np.array([[1, 0],
              [2, 1],
              [0, 3]])

cost = price * qty  # YOUR CODE HERE

bill = np.dot(price, qty)  # YOUR CODE HERE


elem =  A * B  # YOUR CODE HERE
prod = A @ B  # YOUR CODE HERE

PC = P @ C  # YOUR CODE HERE
PC_shape = PC.shape  # YOUR CODE HERE

print("cost", cost)
print("bill", bill)
print("elem", elem)
print("prod", prod)
print("PC", PC)
print("PC_shape", PC_shape)

cost [10.  8. 10. 10.]
bill 38.0
elem [[ 2  0]
 [ 3 12]]
prod [[ 4  6]
 [10 12]]
PC [[ 5 11]
 [14 23]]
PC_shape (2, 2)


**(e) Your answer:**

*Type your answer here.*

## Exercise 6: Absolute values and negation (10 marks)

`err` is a 1-D array of prediction errors, `D` is a 2-D array and `D3` is a 3-D array.
`y_true` and `y_pred` are true and predicted values of a model.

| Part | Task | Marks |
|---|---|---|
| (a) | `abs_err`: the absolute values of `err`. | 2 |
| (b) | `neg_D`: the negation of `D`. | 2 |
| (c) | `abs_D3`: the absolute values of `D3`. | 2 |
| (d) | `mae`: the Mean Absolute Error between `y_true` and `y_pred`. | 2 |
| (e) | `n_big`: how many values of `err` have an absolute value greater than 2. | 2 |

In [25]:
err = np.array([-1.5, 3.0, -2.5, 0.5, 4.0, -0.5])

D = np.array([[ 3, -1],
              [-4,  2]])

D3 = np.array([[[-1,  2], [ 3, -4]],
               [[ 5, -6], [-7,  8]]])

y_true = np.array([10.0, 12.0, 9.0, 15.0])
y_pred = np.array([11.0, 10.0, 9.5, 14.0])

abs_err =  np.abs(err)  # YOUR CODE HERE

neg_D = -D  # YOUR CODE HERE

abs_D3 =  np.abs(D3)  # YOUR CODE HERE

mae = np.mean(np.abs(y_true - y_pred))  # YOUR CODE HERE

n_big = np.sum(np.abs(err) > 2)  # YOUR CODE HERE

print("abs_err", abs_err)
print("neg_D", neg_D)
print("abs_D3", abs_D3)
print("mae", mae)
print("n_big", n_big)

abs_err [1.5 3.  2.5 0.5 4.  0.5]
neg_D [[-3  1]
 [ 4 -2]]
abs_D3 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
mae 1.125
n_big 3


## Exercise 7: Adding and removing elements, rows and columns (10 marks)

Each part starts from the **original** arrays given below.

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `ages_add`: add the value 50 to the end of `ages`. | 2 |
| (b) | 1-D: `ages_del`: remove the element at index 1 from `ages`. | 2 |
| (c) | 2-D: `H_row`: add `new_house` as a new last row of `H`. | 2 |
| (d) | 2-D: `H_col`: add `floors` as a new last column of `H`. | 2 |
| (e) | `H_no_first_col`: remove column 0 from `H`. `H3`: stack `H` and `H2` into a 3-D array. | 2 |

In [26]:
ages = np.array([21, 19, 23, 20])

# 3 houses, 2 features: area (m^2) and number of rooms
H = np.array([[ 85, 2],
              [150, 4],
              [ 60, 1]])
H2 = np.array([[ 90, 3],
               [120, 3],
               [ 70, 2]])

new_house = np.array([110, 3])
floors = np.array([2, 5, 1])

ages_add = np.append(ages, 50)  # YOUR CODE HERE

ages_del =  np.delete(ages, 1)  # YOUR CODE HERE

H_row = np.vstack((H, new_house))  # YOUR CODE HERE

H_col = np.column_stack((H, floors))  # YOUR CODE HERE

H_no_first_col = np.delete(H, 0, axis=1)  # YOUR CODE HERE
H3 = np.stack((H, H2))  # YOUR CODE HERE

print("ages_add", ages_add)
print("ages_del", ages_del)
print("H_row", H_row)
print("H_col", H_col)
print("H_no_first_col", H_no_first_col)
print("H3", H3)
print("H3 shape", None if H3 is None else H3.shape)

ages_add [21 19 23 20 50]
ages_del [21 23 20]
H_row [[ 85   2]
 [150   4]
 [ 60   1]
 [110   3]]
H_col [[ 85   2   2]
 [150   4   5]
 [ 60   1   1]]
H_no_first_col [[2]
 [4]
 [1]]
H3 [[[ 85   2]
  [150   4]
  [ 60   1]]

 [[ 90   3]
  [120   3]
  [ 70   2]]]
H3 shape (2, 3, 2)


## Exercise 8: Maximum, minimum and sum (10 marks)

`temps` is the temperature for 7 days (1-D).
`scores` is the same 4x3 marks table as in Exercise 2 (rows are students, columns are Math, Physics, English).
`sales` is the same 3-D array as in Exercise 3.

| Part | Task | Marks |
|---|---|---|
| (a) | `t_max`, `t_min`, `t_sum`: the highest, lowest and total of `temps`. | 2 |
| (b) | `hottest_day`: the **index** of the highest temperature. | 2 |
| (c) | `student_total`: the total marks of each student (4 values). | 2 |
| (d) | `subject_best`: the highest mark in each subject (3 values). | 2 |
| (e) | `class_mean`: the average of the whole `scores` table. `all_sales`: the total of all values in `sales`. | 2 |

In [27]:
temps = np.array([18, 21, 25, 23, 27, 16, 20])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

sales = np.array([[[12,  7, 30,  4],
                   [ 9, 15, 22,  6],
                   [20,  3, 18, 11]],
                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])

t_max =  np.max(temps)  # YOUR CODE HERE
t_min = np.min(temps)  # YOUR CODE HERE
t_sum = np.sum(temps)  # YOUR CODE HERE

hottest_day = np.argmax(temps)  # YOUR CODE HERE

student_total =  np.sum(scores, axis=1)  # YOUR CODE HERE

subject_best = np.max(scores, axis=0)  # YOUR CODE HERE

class_mean = np.mean(scores)  # YOUR CODE HERE
all_sales = np.sum(sales)  # YOUR CODE HERE

print("t_max", t_max)
print("t_min", t_min)
print("t_sum", t_sum)
print("hottest_day", hottest_day)
print("student_total", student_total)
print("subject_best", subject_best)
print("class_mean", class_mean)
print("all_sales", all_sales)

t_max 27
t_min 16
t_sum 150
hottest_day 4
student_total [225 254 205 235]
subject_best [93 88 90]
class_mean 76.58333333333333
all_sales 325


## Exercise 9: Transpose (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | `N_T`: the transpose of `N`, and `N_T_shape`: its shape. | 2 |
| (b) | `u_T_shape`: the shape of the transpose of the 1-D array `u`. Then, in the written cell, explain in one sentence why the shape did or did not change. | 2 |
| (c) | `r_T`: the transpose of the 2-D row `r`, and `r_T_shape`: its shape. | 2 |
| (d) | `back`: `True` if transposing `N` twice gives `N` again. Use `np.array_equal`. | 2 |
| (e) | `G`: the matrix product of `N` transposed with `N` (that is, `N.T @ N`), and `G_shape`: its shape. | 2 |

In [28]:
N = np.array([[1, 2],
              [3, 4],
              [5, 6]])          # shape (3, 2)

u = np.array([7, 8, 9])         # 1-D

r = np.array([[1, 2, 3, 4]])    # 2-D, shape (1, 4)

N_T = N.T  # YOUR CODE HERE
N_T_shape =  N_T.shape  # YOUR CODE HERE

u_T_shape = u.T.shape  # YOUR CODE HERE

r_T =  r.T  # YOUR CODE HERE
r_T_shape = r_T.shape  # YOUR CODE HERE

back = np.array_equal(N.T.T, N)  # YOUR CODE HERE

G =  N.T @ N  # YOUR CODE HERE
G_shape = G.shape  # YOUR CODE HERE

print("N_T", N_T)
print("N_T_shape", N_T_shape)
print("u_T_shape", u_T_shape)
print("r_T", r_T)
print("r_T_shape", r_T_shape)
print("back", back)
print("G", G)
print("G_shape", G_shape)

N_T [[1 3 5]
 [2 4 6]]
N_T_shape (2, 3)
u_T_shape (3,)
r_T [[1]
 [2]
 [3]
 [4]]
r_T_shape (4, 1)
back True
G [[35 44]
 [44 56]]
G_shape (2, 2)


**(b) Your answer:**

*Type your answer here.*

## Exercise 10: Vectorized arithmetic, a small prediction model (10 marks)

Do **not** use `for` loops in this exercise.

A shop predicts its daily sales (in units) from two features: the temperature and the number of visitors. The model is $\hat{y} = X w + b$.

| Part | Task | Marks |
|---|---|---|
| (a) | `celsius_to_f`: convert the 1-D array `celsius` to Fahrenheit using $F = C \times 1.8 + 32$. | 2 |
| (b) | `squares`: the square of every value in `nums`, and `sum_squares`: their total. | 2 |
| (c) | `y_hat`: the predictions of the model for all 5 days, using `X`, `w` and `b`. | 2 |
| (d) | `errors`: the true values `y` minus the predictions `y_hat`. | 2 |
| (e) | `mse`: the Mean Squared Error, the average of the squared errors. | 2 |

In [29]:
celsius = np.array([0, 10, 20, 30, 40])

nums = np.array([1, 2, 3, 4, 5, 6])

# 5 days, 2 features: temperature and visitors (in hundreds)
X = np.array([[20, 3],
              [25, 5],
              [18, 2],
              [30, 6],
              [22, 4]])
y = np.array([52, 75, 40, 96, 60])   # true sales

w = np.array([1.5, 8.0])
b = 2.0

celsius_to_f = celsius * 1.8 + 32  # YOUR CODE HERE

squares =  nums ** 2  # YOUR CODE HERE
sum_squares = np.sum(squares)  # YOUR CODE HERE

y_hat = X @ w + b  # YOUR CODE HERE

errors = y - y_hat  # YOUR CODE HERE

mse = np.mean(errors ** 2)  # YOUR CODE HERE

print("celsius_to_f", celsius_to_f)
print("squares", squares)
print("sum_squares", sum_squares)
print("y_hat", y_hat)
print("errors", errors)
print("mse", mse)

celsius_to_f [ 32.  50.  68.  86. 104.]
squares [ 1  4  9 16 25 36]
sum_squares 91
y_hat [56.  79.5 45.  95.  67. ]
errors [-4.  -4.5 -5.   1.  -7. ]
mse 22.25
